site_name: Overthewire Bandit interactive write-up

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Cheatsheets:
      - Linux commands: https://pin.it/4SyteJ6Je
      - Linux permissions: https://pin.it/7KK8RVwpE
  - Connect:
      - LinkedIn: https://www.linkedin.com/in/lydiaandenga/
      - Github: https://github.com/Andenga
      
